Repository MasterCruelty/robbot, pull requests merged in 2021-11, with the labels that each got.

#32 🚀 ♻️ Refactor
  modules/atm_feature.py
  modules/covid.py
  modules/reminder.py
  modules/weather.py
  utils/dbfunctions.py
  utils/sysfunctions.py
  utils/utility.py
Labels: enhancement, refactor

#37 :bug: Fix /listrobuser
  utils/dbfunctions.py
Labels: bug, medium priority

#38 Bug fix
  utils/controller.py
Labels: bug, Fix
